modLoader="javafml"
loaderVersion="[35,)"
license="tr7zw Protective License"
[[mods]]
modId="skinlayers3d"
version="1.4.1"
displayName="3dSkinLayers"
authors="tr7zw"
description='''
Renders the player skin layer in 3d
'''
[[dependencies.skinlayers3d]] #optional
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="CLIENT"
# Here's another dependency
[[dependencies.skinlayers3d]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,)"
    ordering="NONE"
    side="CLIENT"
