modLoader="javafml"
loaderVersion="[31,)"
license="MIT"
[[mods]]
modId="skinlayers3d"
version="1.3.1"
displayName="3dSkinLayers"
authors="tr7zw"
description='''
Renders the player skin layer in 3d
'''
# Here's another dependency
[[dependencies.skinlayers3d]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.8.9,)"
    ordering="NONE"
    side="CLIENT"
